version: '3.9'
services:
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./backend/src:/api/src
    env_file:
      - ./backend/.env
    restart: always
  db:
    image: mongo:6.0
    container_name: db
    ports:
      - 27017:27017
    restart: always
