version: '3.9'
services:
  frontend:
    container_name: app_frontend
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app-frontend
      - front_node_modules:/app-frontend/node_modules
    restart: always
  backend:
    container_name: app_backend
    build: ./backend
    ports:
      - 5000:5000
    depends_on:
      - db
      - db-seed
    volumes:
      - ./backend/src:/api/src
    env_file:
      - ./backend/.env
    restart: always
  db:
    image: mongo:6.0
    container_name: db
    ports:
      - 27017:27017
    restart: always
  db-seed:
    container_name: db-seed
    build: ./backend/src/database/seeders
    env_file:
      - ./backend/.env
    depends_on:
      - db
volumes:
  front_node_modules:
